server {
    listen 80;

    # 🔥 фронтенд
    location / {
        alias /staticfiles/;
        index index.html;
    }

    # 🔥 API
    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 🔥 admin
    location /admin/ {
        proxy_pass http://backend:8000/admin/;
        proxy_set_header Host $host;
    }

    # 🔥 media
    location /media/ {
        proxy_pass http://backend:8000/media/;
    }
}
FROM nginx:1.22.1
COPY nginx.conf /etc/nginx/templates/default.conf.template